### ISSUE TITLE
添加 setuptools/setuptools-rust 支持

### ISSUE THREAD

**Issue by berberman** [lilydjwg/luoxu#5]
这将有助于打包 luoxu。

**Comment by lilydjwg** [comment]
来个 pr？

**Comment by berberman** [comment]
在把 `luoxu/__main__.py` 和 `luoxu/ls_dialogs.py` 中的 `if __name__ == '__main__` 替换为 `def entry_point():` 时，以下 `setup.py` 工作：

```python
from setuptools import setup, find_packages
from setuptools_rust import Binding, RustExtension
with open('requirements.txt') as f:
    install_requires = f.read().splitlines()
setup(
  name='luoxu',
  version='0.0.0',
  install_requires=install_requires,
  packages=find_packages(),
  entry_points={
  console_scripts': ['luoxu=luoxu.__main__:entry_point', 'luoxu-ls_dialogs=luoxu.ls_dialogs:entry_point']
  },
  rust_extensions=[RustExtension('querytrans', 'querytrans/Cargo.toml')],
  zip_safe=False,
)
```

我不清楚如何更好地处理 `console_scripts` 以及如何拷贝例如 `nobody.jpg` 的数据文件

**Comment by lilydjwg** [comment]
数据文件用 `importlib.resources` 加载就行。entry_point 的话，我觉得没有必要单独安装，直接 `python -m` 就好了。

另外现在都改用 pyproject.toml 了。

**Comment by berberman** [comment]
> 数据文件用 `importlib.resources` 加载就行。entry_point 的话，我觉得没有必要单独安装，直接 `python -m` 就好了。

当 Python 包不是全局安装时，还是需要一个入口点的。

> 另外现在都改用 pyproject.toml 了。

看起来即便使用 pyproject.toml，setuptools-rust 依然需要在 setup.py 中配置。

**Comment by lilydjwg** [comment]
呃，它不支持 pyproject.toml 的吗……
